"""
Auto Knowledge Distillation task for the cognify pipeline.

Automatically generates cross-chunk aggregated knowledge (enumerations,
aggregations, disambiguations, negation statements, Q&A pairs) from document
chunks to improve retrieval precision. This eliminates the need for manually
created supplementary knowledge files.
"""
import asyncio
import json
from collections import defaultdict
import re
from typing import List, Optional
from uuid import uuid5, UUID

from pydantic import BaseModel, Field

from cognee.infrastructure.engine.models.KnowledgeDistillation import KnowledgeDistillation
from cognee.infrastructure.llm.LLMGateway import LLMGateway
from cognee.infrastructure.llm.prompts import render_prompt, read_query_prompt
from cognee.modules.chunking.models.DocumentChunk import DocumentChunk
from cognee.root_dir import get_absolute_path
from cognee.shared.logging_utils import get_logger
from cognee.tasks.storage.add_data_points import add_data_points

logger = get_logger("distill_knowledge")

# Prompt base directory
PROMPTS_DIR = get_absolute_path("./tasks/distillation/prompts")

# Max characters per LLM call (conservative estimate: ~4 chars/token, 6000 tokens)
DEFAULT_CONTEXT_CHAR_LIMIT = 24000


def _get_distillation_model() -> str:
    """Get the distillation model from YAML config.

    Priority: distillation_model > default LLM_MODEL (from .env).
    Note: distillation intentionally does NOT fall back to extraction_model,
    because distillation requires stronger reasoning than extraction.
    """
    try:
        from cognee.infrastructure.config.yaml_config import get_module_config
        model_cfg = get_module_config("model_selection").get("models", {})
        distillation_model = model_cfg.get("distillation_model", "")
        if distillation_model:
            return distillation_model
    except Exception:
        pass
    # Fall back to default LLM_MODEL (typically qwen-plus)
    from cognee.infrastructure.llm.config import get_llm_config
    return get_llm_config().llm_model


def _get_profiling_model() -> str:
    """Get the model for document profiling (Stage 1).

    Uses extraction_model (turbo) since profiling is a simple structural
    analysis task that does not require strong reasoning.
    """
    try:
        from cognee.infrastructure.config.yaml_config import get_module_config
        model_cfg = get_module_config("model_selection").get("models", {})
        extraction_model = model_cfg.get("extraction_model", "")
        if extraction_model:
            return extraction_model
    except Exception:
        pass
    from cognee.infrastructure.llm.config import get_llm_config
    return get_llm_config().llm_model


def _is_profiling_enabled() -> bool:
    """Check if document profiling is enabled in YAML config."""
    try:
        from cognee.infrastructure.config.yaml_config import get_module_config
        config = get_module_config("distillation")
        profiling = config.get("distillation", {}).get("profiling", {})
        return profiling.get("enabled", True)
    except Exception:
        return True


def _get_profiling_preview_chars() -> int:
    """Get the number of preview characters for profiling."""
    try:
        from cognee.infrastructure.config.yaml_config import get_module_config
        config = get_module_config("distillation")
        profiling = config.get("distillation", {}).get("profiling", {})
        return profiling.get("preview_chars", 3000)
    except Exception:
        return 3000


class DistillationItem(BaseModel):
    """Single distillation item returned by the LLM."""
    type: str = Field(description="Distillation type: enumeration, aggregation, disambiguation, negation, or qa")
    text: str = Field(description="The distilled knowledge content")


class DistillationResponse(BaseModel):
    """Structured response from the LLM containing all distillation items."""
    items: List[DistillationItem] = Field(
        description="List of knowledge distillation items",
        default_factory=list,
    )


class DocumentProfile(BaseModel):
    """Structured profile of a document from Stage 1 profiling.

    Generated by a fast model to understand document structure and provide
    domain-specific guidance for the distillation stage.
    All fields have defaults so that partial profiles still work.
    """
    doc_type: str = Field(default="general", description="Document type")
    language: str = Field(default="zh", description="Primary language code")
    key_categories: List[str] = Field(default_factory=list, description="Main topic areas")
    enumeration_targets: List[str] = Field(default_factory=list, description="Lists to enumerate")
    role_parties: List[str] = Field(default_factory=list, description="Parties/roles involved")
    example_questions: List[str] = Field(default_factory=list, description="Likely reader questions")
    qa_coverage_areas: List[str] = Field(default_factory=list, description="Domain-specific QA coverage areas")
    disambiguation_pairs: List[str] = Field(default_factory=list, description="Confusable concept pairs")


async def distill_knowledge(
    data_chunks: List[DocumentChunk],
    context_char_limit: int = DEFAULT_CONTEXT_CHAR_LIMIT,
) -> List[DocumentChunk]:
    """
    Generate knowledge distillations from document chunks.

    Groups chunks by document, sends each document's combined text to an LLM
    for knowledge distillation, stores the results as KnowledgeDistillation
    DataPoints, and returns the original chunks unchanged.

    This task follows the same pattern as extract_graph_from_data:
    - Internally calls add_data_points() to store generated knowledge
    - Returns original data_chunks unchanged for downstream tasks

    Parameters:
    -----------
        data_chunks: List of DocumentChunk objects from the pipeline.
        context_char_limit: Maximum characters per LLM call.
            Documents exceeding this limit are processed in batches
            with a final merge pass.

    Returns:
    --------
        The original list of DocumentChunk objects (unchanged).
    """
    if not data_chunks:
        return data_chunks

    # Group chunks by document_id
    doc_chunks_map = defaultdict(list)
    for chunk in data_chunks:
        doc_id = _get_document_id(chunk)
        doc_chunks_map[doc_id].append(chunk)

    logger.info(
        f"Knowledge distillation: processing {len(doc_chunks_map)} document(s) "
        f"from {len(data_chunks)} chunk(s)"
    )

    # Process each document
    all_distillation_points = []
    tasks = []

    for doc_id, chunks in doc_chunks_map.items():
        tasks.append(
            _distill_single_document(doc_id, chunks, context_char_limit)
        )

    # Use semaphore to limit concurrent LLM calls
    semaphore = asyncio.Semaphore(3)

    async def _limited_distill(coro):
        async with semaphore:
            return await coro

    results = await asyncio.gather(
        *[_limited_distill(task) for task in tasks],
        return_exceptions=True,
    )

    for doc_id, result in zip(doc_chunks_map.keys(), results):
        if isinstance(result, Exception):
            logger.error(f"Distillation failed for document {doc_id}: {result}")
            continue
        all_distillation_points.extend(result)

    # Store distillation points in vector index
    if all_distillation_points:
        await add_data_points(all_distillation_points)
        logger.info(
            f"Knowledge distillation complete: "
            f"{len(all_distillation_points)} distillation points stored"
        )
    else:
        logger.warning("Knowledge distillation produced no results")

    # Return original chunks unchanged (same pattern as extract_graph_from_data)
    return data_chunks


def _get_document_id(chunk: DocumentChunk) -> UUID:
    """Extract the document ID from a chunk."""
    if hasattr(chunk, 'is_part_of') and chunk.is_part_of is not None:
        return chunk.is_part_of.id
    # Fallback: use chunk's own ID
    return chunk.id


def _get_document_name(chunks: List[DocumentChunk]) -> str:
    """Extract the document name from chunks.

    Tries to get the name from the Document object (is_part_of.name),
    then falls back to source_file_path, then returns empty string.
    Strips common file extensions for cleaner display.
    """
    for chunk in chunks:
        # Try Document.name via is_part_of
        if hasattr(chunk, 'is_part_of') and chunk.is_part_of is not None:
            doc = chunk.is_part_of
            if hasattr(doc, 'name') and doc.name:
                name = doc.name
                # Strip common extensions
                for ext in ['.pdf', '.docx', '.doc', '.txt', '.md', '.html']:
                    if name.lower().endswith(ext):
                        name = name[:-len(ext)]
                return name.strip()
        # Try source_file_path
        if hasattr(chunk, 'source_file_path') and chunk.source_file_path:
            import os
            name = os.path.basename(chunk.source_file_path)
            for ext in ['.pdf', '.docx', '.doc', '.txt', '.md', '.html']:
                if name.lower().endswith(ext):
                    name = name[:-len(ext)]
            return name.strip()
    return ""


def _split_long_enumerations(items: List[DistillationItem]) -> List[DistillationItem]:
    """
    Split long enumeration items into summary + full versions.

    For enumeration items exceeding 300 characters, generates an additional
    summary item containing only the first line (typically the count/title).
    This improves vector search matching: "how many X?" matches the short
    summary, while "what are all the X?" matches the full list.
    """
    result = []
    for item in items:
        result.append(item)
        if item.type == "enumeration" and len(item.text) > 300:
            # Extract the first line as a summary
            first_line = item.text.split("\n")[0].strip()
            if first_line and len(first_line) < len(item.text):
                result.append(DistillationItem(
                    type="enumeration",
                    text=first_line,
                ))
    return result


async def _profile_document(document_text: str) -> Optional[DocumentProfile]:
    """
    Stage 1: Profile the document to understand its structure.

    Uses a fast/cheap model (turbo) with truncated input.
    Only 1 call per document (not per chunk).
    Returns None if profiling fails (caller falls back to static prompt).
    """
    import litellm
    from cognee.infrastructure.llm.config import get_llm_config

    litellm.drop_params = True

    # Truncate to save tokens (0 means use full document)
    preview_chars = _get_profiling_preview_chars()
    if preview_chars > 0 and len(document_text) > preview_chars:
        preview_text = document_text[:preview_chars]
        preview_text += "\n\n[... 文档后续内容省略 / document continues ...]"
    else:
        preview_text = document_text

    system_prompt = read_query_prompt(
        "profile_document_system.txt",
        base_directory=PROMPTS_DIR,
    )
    if not system_prompt:
        logger.warning("Profile system prompt not found, skipping profiling")
        return None

    context = {"document_preview": preview_text}
    text_input = render_prompt(
        "profile_document_input.txt",
        context,
        base_directory=PROMPTS_DIR,
    )

    llm_config = get_llm_config()
    effective_model = _get_profiling_model()
    logger.info(f"Document profiling: model={effective_model}, preview_chars={len(preview_text)}")

    try:
        response = await litellm.acompletion(
            model=effective_model,
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": text_input},
            ],
            api_key=llm_config.llm_api_key,
            api_base=llm_config.llm_endpoint,
            temperature=0.0,
            timeout=60,
            stream=True,
        )

        full_response = ""
        async for chunk in response:
            delta = chunk.choices[0].delta
            if delta and delta.content:
                full_response += delta.content

        if not full_response:
            logger.warning("Profiling returned empty response")
            return None

        profile = _parse_profile_response(full_response)
        if profile:
            logger.info(
                f"Document profiled: type={profile.doc_type}, "
                f"categories={len(profile.key_categories)}, "
                f"enum_targets={len(profile.enumeration_targets)}, "
                f"qa_areas={len(profile.qa_coverage_areas)}, "
                f"questions={len(profile.example_questions)}"
            )
        return profile

    except Exception as e:
        logger.warning(f"Document profiling failed: {e}")
        return None


def _parse_profile_response(response_text: str) -> Optional[DocumentProfile]:
    """Parse profiling LLM response into DocumentProfile."""
    text = response_text.strip()

    # Extract from markdown code blocks
    if "```" in text:
        json_match = re.search(r'```(?:json)?\s*([\s\S]*?)```', text)
        if json_match:
            text = json_match.group(1).strip()

    # Try direct JSON parse
    try:
        parsed = json.loads(text)
        return DocumentProfile.model_validate(parsed)
    except Exception:
        pass

    # Fallback: extract JSON object substring
    start_idx = text.find('{')
    end_idx = text.rfind('}')
    if start_idx != -1 and end_idx > start_idx:
        try:
            parsed = json.loads(text[start_idx:end_idx + 1])
            return DocumentProfile.model_validate(parsed)
        except Exception:
            pass

    logger.warning(f"Failed to parse profiling response: {text[:200]}")
    return None


def _build_profile_context(profile: DocumentProfile) -> dict:
    """Convert DocumentProfile into a Jinja2 template context dict."""
    return {
        "has_profile": True,
        "doc_type": profile.doc_type,
        "language": profile.language,
        "key_categories": profile.key_categories,
        "enumeration_targets": profile.enumeration_targets,
        "role_parties": profile.role_parties,
        "example_questions": profile.example_questions,
        "qa_coverage_areas": profile.qa_coverage_areas,
        "disambiguation_pairs": profile.disambiguation_pairs,
    }


async def _distill_single_document(
    doc_id: UUID,
    chunks: List[DocumentChunk],
    context_char_limit: int,
) -> List[KnowledgeDistillation]:
    """
    Distill knowledge from a single document's chunks.

    If the combined text exceeds context_char_limit, uses hierarchical
    distillation (map-reduce pattern):
    1. First pass: distill batches of chunks
    2. Second pass: merge batch distillations into final result
    """
    # Sort chunks by index for proper ordering
    sorted_chunks = sorted(chunks, key=lambda c: getattr(c, 'chunk_index', 0))
    combined_text = "\n\n".join(chunk.text for chunk in sorted_chunks)

    # Extract document name for source tagging
    doc_name = _get_document_name(sorted_chunks)

    # Stage 1: Profile the document (dynamic prompt generation)
    profile = None
    if _is_profiling_enabled():
        profile = await _profile_document(combined_text)

    if len(combined_text) <= context_char_limit:
        # Single-pass distillation
        items = await _call_llm_distill(combined_text, profile=profile)
    else:
        # Hierarchical distillation for large documents
        items = await _hierarchical_distill(sorted_chunks, context_char_limit, profile=profile)

    # Post-processing: split long enumerations into summary + full versions
    items = _split_long_enumerations(items)

    # Convert to KnowledgeDistillation DataPoints
    distillation_points = []
    for idx, item in enumerate(items):
        # Generate deterministic UUID from doc_id + index
        point_id = uuid5(doc_id, f"KnowledgeDistillation_{idx}")

        # Add document source prefix to help multi-document disambiguation.
        # When multiple documents discuss the same topic (e.g., different 甲方),
        # this prefix helps the retrieval system match the correct document.
        text = item.text
        if doc_name:
            text = f"[来源: {doc_name}] {text}"

        point = KnowledgeDistillation(
            id=point_id,
            text=text,
            source_document_id=doc_id,
            distillation_type=item.type,
        )
        distillation_points.append(point)

    logger.info(
        f"Document {doc_id} ({doc_name or 'unnamed'}): "
        f"generated {len(distillation_points)} distillation points "
        f"from {len(chunks)} chunks"
    )
    return distillation_points


async def _hierarchical_distill(
    chunks: List[DocumentChunk],
    context_char_limit: int,
    profile: Optional[DocumentProfile] = None,
) -> List[DistillationItem]:
    """
    Hierarchical distillation for large documents.

    Splits chunks into batches that fit within context_char_limit,
    distills each batch, then merges all batch results in a final pass.
    """
    # Split into batches
    batches = []
    current_batch = []
    current_length = 0

    for chunk in chunks:
        chunk_len = len(chunk.text)
        if current_length + chunk_len > context_char_limit and current_batch:
            batches.append(current_batch)
            current_batch = [chunk]
            current_length = chunk_len
        else:
            current_batch.append(chunk)
            current_length += chunk_len + 2  # +2 for "\n\n" separator

    if current_batch:
        batches.append(current_batch)

    logger.info(
        f"Hierarchical distillation: {len(chunks)} chunks split into {len(batches)} batches"
    )

    # First pass: distill each batch
    batch_results = []
    for batch in batches:
        batch_text = "\n\n".join(chunk.text for chunk in batch)
        items = await _call_llm_distill(batch_text, profile=profile)
        batch_results.extend(items)

    # If only one batch, no merge needed
    if len(batches) <= 1:
        return batch_results

    # Second pass: merge all batch results using merge-specific prompt
    merge_text = "\n\n".join(
        f"[{item.type.upper()}] {item.text}" for item in batch_results
    )

    if len(merge_text) <= context_char_limit:
        # Merge all at once
        merged_items = await _call_llm_merge(merge_text)
        return merged_items
    else:
        # Split merge text into groups and merge each group, then merge groups
        logger.info(
            "Merge text exceeds context limit, performing grouped merge"
        )
        # Split batch_results into groups that fit within context_char_limit
        merge_groups = []
        current_group = []
        current_len = 0
        for item in batch_results:
            item_text = f"[{item.type.upper()}] {item.text}"
            item_len = len(item_text)
            if current_len + item_len > context_char_limit and current_group:
                merge_groups.append(current_group)
                current_group = [item]
                current_len = item_len
            else:
                current_group.append(item)
                current_len += item_len + 2
        if current_group:
            merge_groups.append(current_group)

        # Merge each group
        group_merged = []
        for group in merge_groups:
            group_text = "\n\n".join(
                f"[{item.type.upper()}] {item.text}" for item in group
            )
            merged = await _call_llm_merge(group_text)
            group_merged.extend(merged)

        # If we ended up with multiple groups, try a final merge
        if len(merge_groups) > 1:
            final_text = "\n\n".join(
                f"[{item.type.upper()}] {item.text}" for item in group_merged
            )
            if len(final_text) <= context_char_limit:
                return await _call_llm_merge(final_text)

        return group_merged


async def _call_llm_distill(
    document_text: str,
    profile: Optional[DocumentProfile] = None,
) -> List[DistillationItem]:
    """
    Call the LLM to generate knowledge distillations from document text.

    Uses litellm streaming mode to avoid DashScope server disconnecting
    on long-running requests (large documents can take 2+ minutes to distill,
    exceeding non-streaming connection timeouts).

    When a DocumentProfile is provided, both system and input prompts are
    rendered with profiling context via Jinja2, adding domain-specific guidance.
    Without a profile, the Jinja2 conditional blocks are skipped, producing
    output identical to the original static universal prompt.

    Returns a list of DistillationItem objects.
    """
    import litellm
    from cognee.infrastructure.llm.config import get_llm_config

    litellm.drop_params = True

    # Build prompt context based on whether profiling succeeded
    if profile:
        prompt_context = _build_profile_context(profile)
    else:
        prompt_context = {"has_profile": False}

    # Render system prompt via Jinja2 (dynamic section included when has_profile=True)
    system_prompt = render_prompt(
        "distill_knowledge_system.txt",
        prompt_context,
        base_directory=PROMPTS_DIR,
    )

    # Render input prompt with document text + profiling context
    input_context = {"document_text": document_text, **prompt_context}
    text_input = render_prompt(
        "distill_knowledge_input.txt",
        input_context,
        base_directory=PROMPTS_DIR,
    )

    llm_config = get_llm_config()
    effective_model = _get_distillation_model()
    logger.info(f"Using model: {effective_model} for distillation")

    try:
        # Use streaming to keep connection alive during long distillation
        response = await litellm.acompletion(
            model=effective_model,
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": text_input},
            ],
            api_key=llm_config.llm_api_key,
            api_base=llm_config.llm_endpoint,
            temperature=llm_config.llm_temperature,
            timeout=300,
            stream=True,
        )

        # Collect streamed response
        full_response = ""
        async for chunk in response:
            delta = chunk.choices[0].delta
            if delta and delta.content:
                full_response += delta.content

        if not full_response:
            logger.warning("LLM returned empty response for distillation")
            return []

        logger.info(f"Distillation LLM response: {len(full_response)} chars")
        return _parse_distillation_response(full_response)

    except Exception as e:
        logger.error(f"LLM distillation call failed: {e}")
        return []


async def _call_llm_merge(distillation_text: str) -> List[DistillationItem]:
    """
    Call the LLM to merge batch distillation results.

    Uses merge-specific prompts that tell the LLM it's merging already-distilled
    knowledge items, not distilling raw document text.

    Returns a list of DistillationItem objects.
    """
    import litellm
    from cognee.infrastructure.llm.config import get_llm_config

    litellm.drop_params = True

    # Load merge-specific prompts
    system_prompt = read_query_prompt(
        "merge_distillation_system.txt",
        base_directory=PROMPTS_DIR,
    )

    context = {"distillation_results": distillation_text}
    text_input = render_prompt(
        "merge_distillation_input.txt",
        context,
        base_directory=PROMPTS_DIR,
    )

    llm_config = get_llm_config()
    effective_model = _get_distillation_model()
    logger.info(f"Using model: {effective_model} for merge")

    try:
        response = await litellm.acompletion(
            model=effective_model,
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": text_input},
            ],
            api_key=llm_config.llm_api_key,
            api_base=llm_config.llm_endpoint,
            temperature=llm_config.llm_temperature,
            timeout=300,
            stream=True,
        )

        full_response = ""
        async for chunk in response:
            delta = chunk.choices[0].delta
            if delta and delta.content:
                full_response += delta.content

        if not full_response:
            logger.warning("LLM returned empty response for merge")
            return []

        logger.info(f"Merge LLM response: {len(full_response)} chars")
        return _parse_distillation_response(full_response)

    except Exception as e:
        logger.error(f"LLM merge call failed: {e}")
        return []


def _parse_distillation_response(response_text: str) -> List[DistillationItem]:
    """
    Parse the LLM's text response into DistillationItem objects.

    Handles multiple JSON formats:
    1. JSON array: [{"type": "...", "text": "..."}, ...]
    2. JSON object with 'items' key: {"items": [...]}
    3. JSON embedded in markdown code blocks: ```json ... ```
    """
    valid_types = {"enumeration", "aggregation", "disambiguation", "negation", "qa"}
    text = response_text.strip()

    # Extract JSON from markdown code blocks if present
    if "```" in text:
        json_match = re.search(r'```(?:json)?\s*([\s\S]*?)```', text)
        if json_match:
            text = json_match.group(1).strip()

    try:
        parsed = json.loads(text)
    except json.JSONDecodeError:
        # Try to find JSON array or object in the text
        for start_char, end_char in [('[', ']'), ('{', '}')]:
            start_idx = text.find(start_char)
            end_idx = text.rfind(end_char)
            if start_idx != -1 and end_idx != -1 and end_idx > start_idx:
                try:
                    parsed = json.loads(text[start_idx:end_idx + 1])
                    break
                except json.JSONDecodeError:
                    continue
        else:
            logger.error(f"Failed to parse JSON from LLM response (first 200 chars): {text[:200]}")
            return []

    # Normalize to list of items
    items_list = []
    if isinstance(parsed, list):
        items_list = parsed
    elif isinstance(parsed, dict):
        if 'items' in parsed:
            items_list = parsed['items']
        else:
            # Single item
            items_list = [parsed]

    # Validate and convert
    valid_items = []
    for raw_item in items_list:
        if not isinstance(raw_item, dict):
            continue
        item_type = raw_item.get('type', '').strip().lower()
        item_text = raw_item.get('text', '').strip()

        if item_type not in valid_types:
            logger.warning(f"Unknown distillation type '{item_type}', skipping")
            continue
        if not item_text:
            continue

        valid_items.append(DistillationItem(type=item_type, text=item_text))

    logger.info(f"Parsed {len(valid_items)} valid distillation items from LLM response")
    return valid_items
