import base64
import instructor
from typing import Type
from pydantic import BaseModel
from openai import AsyncOpenAI, OpenAI, ContentFilterFinishReasonError, APIConnectionError, APITimeoutError
from instructor.core import InstructorRetryException

import logging
from tenacity import (
    retry,
    stop_after_delay,
    wait_exponential_jitter,
    retry_if_exception_type,
    before_sleep_log,
)

from cognee.infrastructure.llm.structured_output_framework.litellm_instructor.llm.llm_interface import (
    LLMInterface,
)
from cognee.infrastructure.llm.exceptions import (
    ContentPolicyFilterError,
)
from cognee.infrastructure.files.utils.open_data_file import open_data_file
from cognee.modules.observability.get_observe import get_observe
from cognee.shared.logging_utils import get_logger
from cognee.infrastructure.llm.config import get_llm_config

logger = get_logger()

observe = get_observe()


class OpenAIAdapter(LLMInterface):
    """
    Adapter for OpenAI's GPT-3, GPT-4 API.

    Public methods:

    - acreate_structured_output
    - create_structured_output
    - create_transcript
    - transcribe_image
    - show_prompt

    Instance variables:

    - name
    - model
    - api_key
    - api_version
    - MAX_RETRIES
    """

    name = "OpenAI"
    model: str
    api_key: str
    api_version: str

    MAX_RETRIES = 5

    """Adapter for OpenAI's GPT-3, GPT=4 API"""

    def __init__(
        self,
        api_key: str,
        endpoint: str,
        api_version: str,
        model: str,
        transcription_model: str,
        max_completion_tokens: int,
        streaming: bool = False,
        fallback_model: str = None,
        fallback_api_key: str = None,
        fallback_endpoint: str = None,
    ):
        # Build OpenAI clients with explicit base_url and api_key
        client_kwargs = {"api_key": api_key or ""}
        if endpoint:
            client_kwargs["base_url"] = endpoint

        async_client = AsyncOpenAI(**client_kwargs)
        sync_client = OpenAI(**client_kwargs)

        mode = instructor.Mode.JSON_SCHEMA if "gpt-5" in model else instructor.Mode.TOOLS
        self.aclient = instructor.from_openai(async_client, mode=mode)
        self.client = instructor.from_openai(sync_client, mode=mode)

        # Keep raw clients for transcription/image calls
        self._async_client = async_client
        self._sync_client = sync_client

        self.transcription_model = transcription_model
        self.model = model
        self.api_key = api_key
        self.endpoint = endpoint
        self.api_version = api_version
        self.max_completion_tokens = max_completion_tokens
        self.streaming = streaming

        self.fallback_model = fallback_model
        self.fallback_api_key = fallback_api_key
        self.fallback_endpoint = fallback_endpoint

        # Build fallback client if configured
        self._fallback_aclient = None
        if fallback_model and fallback_api_key:
            fb_kwargs = {"api_key": fallback_api_key}
            if fallback_endpoint:
                fb_kwargs["base_url"] = fallback_endpoint
            fb_async = AsyncOpenAI(**fb_kwargs)
            self._fallback_aclient = instructor.from_openai(fb_async, mode=mode)

    @observe(as_type="generation")
    @retry(
        stop=stop_after_delay(128),
        wait=wait_exponential_jitter(2, 128),
        retry=retry_if_exception_type((APIConnectionError, APITimeoutError, ConnectionError)),
        before_sleep=before_sleep_log(logger, logging.DEBUG),
        reraise=True,
    )
    async def acreate_structured_output(
        self, text_input: str, system_prompt: str, response_model: Type[BaseModel]
    ) -> BaseModel:
        """
        Generate a response from a user query.

        Parameters:
        -----------

            - text_input (str): The input text provided by the user for generating a response.
            - system_prompt (str): The system's prompt to guide the model's response.
            - response_model (Type[BaseModel]): The expected model type for the response.

        Returns:
        --------

            - BaseModel: A structured output generated by the model.
        """

        try:
            return await self.aclient.chat.completions.create(
                model=self.model,
                messages=[
                    {
                        "role": "user",
                        "content": f"""{text_input}""",
                    },
                    {
                        "role": "system",
                        "content": system_prompt,
                    },
                ],
                response_model=response_model,
                max_retries=self.MAX_RETRIES,
                temperature=get_llm_config().llm_temperature,
            )
        except (
            ContentFilterFinishReasonError,
            InstructorRetryException,
        ) as e:
            if not self._fallback_aclient:
                raise e
            try:
                return await self._fallback_aclient.chat.completions.create(
                    model=self.fallback_model,
                    messages=[
                        {
                            "role": "user",
                            "content": f"""{text_input}""",
                        },
                        {
                            "role": "system",
                            "content": system_prompt,
                        },
                    ],
                    response_model=response_model,
                    max_retries=self.MAX_RETRIES,
                    temperature=get_llm_config().llm_temperature,
                )
            except (
                ContentFilterFinishReasonError,
                InstructorRetryException,
            ) as error:
                if (
                    isinstance(error, InstructorRetryException)
                    and "content management policy" not in str(error).lower()
                ):
                    raise error
                else:
                    raise ContentPolicyFilterError(
                        f"The provided input contains content that is not aligned with our content policy: {text_input}"
                    ) from error

    @observe
    @retry(
        stop=stop_after_delay(128),
        wait=wait_exponential_jitter(2, 128),
        retry=retry_if_exception_type((APIConnectionError, APITimeoutError, ConnectionError)),
        before_sleep=before_sleep_log(logger, logging.DEBUG),
        reraise=True,
    )
    def create_structured_output(
        self, text_input: str, system_prompt: str, response_model: Type[BaseModel]
    ) -> BaseModel:
        """
        Generate a response from a user query (synchronous).
        """

        return self.client.chat.completions.create(
            model=self.model,
            messages=[
                {
                    "role": "user",
                    "content": f"""{text_input}""",
                },
                {
                    "role": "system",
                    "content": system_prompt,
                },
            ],
            response_model=response_model,
            max_retries=self.MAX_RETRIES,
            temperature=get_llm_config().llm_temperature,
        )

    @retry(
        stop=stop_after_delay(128),
        wait=wait_exponential_jitter(2, 128),
        retry=retry_if_exception_type((APIConnectionError, APITimeoutError, ConnectionError)),
        before_sleep=before_sleep_log(logger, logging.DEBUG),
        reraise=True,
    )
    async def create_transcript(self, input):
        """
        Generate an audio transcript from a user query.
        """
        async with open_data_file(input, mode="rb") as audio_file:
            transcription = await self._async_client.audio.transcriptions.create(
                model=self.transcription_model,
                file=audio_file,
            )

        return transcription

    @retry(
        stop=stop_after_delay(128),
        wait=wait_exponential_jitter(2, 128),
        retry=retry_if_exception_type((APIConnectionError, APITimeoutError, ConnectionError)),
        before_sleep=before_sleep_log(logger, logging.DEBUG),
        reraise=True,
    )
    async def transcribe_image(self, input) -> BaseModel:
        """
        Generate a transcription of an image from a user query.
        """
        async with open_data_file(input, mode="rb") as image_file:
            encoded_image = base64.b64encode(image_file.read()).decode("utf-8")

        response = await self._async_client.chat.completions.create(
            model=self.model,
            messages=[
                {
                    "role": "user",
                    "content": [
                        {
                            "type": "text",
                            "text": "What's in this image?",
                        },
                        {
                            "type": "image_url",
                            "image_url": {
                                "url": f"data:image/jpeg;base64,{encoded_image}",
                            },
                        },
                    ],
                }
            ],
            max_tokens=300,
        )
        return response
